### ISSUE TITLE
API for add and delete multiple streams

### ISSUE THREAD

**Issue by lfarkas** [deepch/RTSPtoWeb#10]
it'd be useful if i can add and delete multiple streams ones.

- when i add more streams the also add it's channels so eg. i can add 16 streams each with 2 channels.
- delete 16 streams. when i delete a stream of course delete all of it's channels too.

**Comment by EugeneTV** [comment]
Множественное редактирование тоже было бы не лишним. У нас сервер Cisco VSM отдает потоки с динамическими адреса ограниченными по времени жизни, приходится периодически перезапрашивать новые адреса потоков.
