### ISSUE TITLE
Stream with ffmpeg is like ripped

### ISSUE THREAD

**Issue by Dream4Theater** [deepch/RTSPtoWeb#136]
I stream my camera to https://github.com/aler9/rtsp-simple-server and then i wanna shwo with rtsptoweb but video is like have 3 pieces and middle one is lagging sometimes have a green screen idk something happening there

I stream with this code "ffmpeg -f dshow -i video="Integrated Camera" -g 25 -s 320x240 -vcodec libx264 -b:v 500k -preset ultrafast -tune:v zerolatency -f rtsp -rtsp_transport tcp rtsp://<ip-adress>:<port>/stream"

![image](https://user-images.githubusercontent.com/81992744/161275347-214f8932-eeff-4faf-b30c-096ac5adeed9.png)

**Comment by deepch** [comment]
-tune:v zerolatency work only thread=1

**Comment by Dream4Theater** [comment]
thanks using -threads 1 solved problem
