### ISSUE TITLE
How to Record Rstp stream

### ISSUE THREAD

**Issue by gaoluhua99** [deepch/RTSPtoWeb#14]
Dear sir,
   can you make a new software for recording the rstp resource.  thank you

**Comment by deepch** [comment]
for window or linux os?

**Comment by deepch** [comment]
This functionality is not provided by this software

**Comment by gaoluhua99** [comment]
the better is for linux .Can you make one for us. Best wishes!

**Comment by deepch** [comment]
Good afternoon, I can, but this is too much work.

**Comment by gaoluhua99** [comment]
No rush, take your time. Thank you very much.
