### ISSUE TITLE
Multiview no Streams Avilable

### ISSUE THREAD

**Issue by ZelleAP** [deepch/RTSPtoWeb#16]
Although I have created streams, they are not available for Multiview. Tested with Chrome, Firefox and Microsoft Edge.

![no_streams_aviable](https://user-images.githubusercontent.com/31035671/104895804-9d007d00-5976-11eb-9d50-18411ffeaa04.PNG)

**Comment by deepch** [comment]
while what do you have in the config? have you added streams?

**Comment by ZelleAP** [comment]
Hi deepch,

this is my config:
{
  "server": {
    "debug": true,
    "http_debug": true,
    "http_demo": true,
    "http_dir": "web",
    "http_login": "demo",
    "http_password": "demo",
    "http_port": ":8083",
    "log_level": "debug",
    "rtsp_port": ":5541"
  },
  "streams": {
    "0c4b1072-934c-4998-b0f4-2002cb152cc9": {
      "channels": {
        "0": {
          "url": "rtsp://admin:admin@192.168.99.55/live1.sdp"
        }
      },
      "name": "D-Link"
    },
    "124e7f84-14c1-477f-9cae-71de19249a7c": {
      "channels": {
        "0": {
          "url": "rtsp://admin:admin@192.168.30.73:554/S1"
        }
      },
      "name": "E150"
    },
    "31d5a1f2-32a7-45a3-b08d-3040487b7a9a": {
      "channels": {
        "0": {
          "on_demand": true,
          "url": "rtsp://admin:admin@10.10.77.16/axis-media/media.amp"
        }
      },
      "name": "Axis Kanada"
    },
    "33142021-e06d-40c1-87fd-19a5ab162fd3": {
      "channels": {
        "0": {
          "on_demand": true,
          "url": "rtsp://admin:admin!@192.168.30.202"
        }
      },
      "name": "UG Corridor"
    },
    "dcc79017-4acc-4d53-92c9-97ccdc51f50c": {
      "channels": {
        "0": {
          "debug": true,
          "on_demand": true,
          "url": "rtsp://admin:admin@192.168.30.203/defaultPrimary?mtu=1440\u0026streamType=u"
        }
      },
      "name": "UG room"
    },
    "test": {
      "channels": {
        "0": {
          "on_demand": true,
          "url": "rtsp://admin:admin@192.168.30.201"
        }
      },
      "name": "EG entrance"
    }
  }
}

**Comment by ZelleAP** [comment]
Installed Version: v0.0.0-20210106145838-3c9911e11bd4

**Comment by vdalex25** [comment]
fixed

**Comment by deepch** [comment]
https://github.com/deepch/RTSPtoWeb/commit/275910ee8452f396f15b7f62abbc899a25e1b4c6
