### ISSUE TITLE
DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.

### ISSUE THREAD

**Issue by habr** [deepch/RTSPtoWeb#169]
DOMException: Failed to execute 'appendBuffer' on 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at msePlayer.readPacket (http://127.0.0.1:8083/pages/multiview/full?controls:681:34)
    at WebSocket._this.ws.onmessage (http://127.0.0.1:8083/pages/multiview/full?controls:615:19)

**Comment by tatjanara** [comment]
I have the same problem. After some check we have notice that this was a behavior on a pc with lower performance. (16gb RAM memory) It seams that browser can't deal good enough with packets if pc doesn't have high performance. Is it possible?
