### ISSUE TITLE
Endless Spinner with latest Firefox 84.0.2

### ISSUE THREAD

**Issue by ZelleAP** [deepch/RTSPtoWeb#17]
After the stream has started, the spinner should disappear, this works in Chrome and Edge but not in the latest Firefox.

![spinner](https://user-images.githubusercontent.com/31035671/104927009-30e73e80-59a1-11eb-8718-7dcf78bb9c6d.PNG)

**Comment by vdalex25** [comment]
fixed https://github.com/deepch/RTSPtoWeb/commit/2bca0c71ab36ecc02e37bffbd329c9910c73841e
