### ISSUE TITLE
Streams jerking with WebRTC and HLS

### ISSUE THREAD

**Issue by ZelleAP** [deepch/RTSPtoWeb#19]
In my tests I found that MSE works very well. Unfortunately, I can't say the same for WebRTC and HLS, the streams stop every few seconds. Are there any tweaks that can be applied here? For example, higher buffer etc.?

**Comment by deepch** [comment]
This is very strange, but is there any error in the logs? Perhaps the player is not sending a keep-alive request?

**Comment by ZelleAP** [comment]
I get the following error messages in debug mode for an encoder:
2021/02/11 09:59:30 [Unsuported Intervaled data packet 1 [8 24 97 32 128 32 82 35 0 0 48 201 0 238 49 130 129 202 0 9 55 88 197 191 1 29 86 117 83 116 114 101 97 109 49 53 48 45 48 50 58 48 54 58 48 53 58 49 100 58 48 48 58 50 50 0]]
2021/02/11 09:59:30 [Unsupported NAL Type 6]

Do you have any idea what the problem is?

**Comment by deepch** [comment]
no problem, disable debug 

nal -> 6 | Supplemental enhancement information (SEI)sei_rbsp( ) | 5 | non-VCL | non-VCL | non-VCL

no need for play
