### ISSUE TITLE
Is it possible to embed the WebRTC endpoint in an iframe?

### ISSUE THREAD

**Issue by antoniosteiger** [deepch/RTSPtoWeb#200]
Hi,

thank you for writing this software, it looks very promising to me. I am trying to understand how I could use it on a webapplication I am writing. There, I want to embed the WebRTC stream created with your code in an iframe. Is that possible?
I would just embed this address from your API:

http://127.0.0.1:8083/stream/{STREAM_ID}/channel/{CHANNEL_ID}/webrtc

Resulting in:

```
<iframe ng-controller="EmbeddedPageController as ctl" ng-src="http://127.0.0.1:8083/stream/{STREAM_ID}/channel/{CHANNEL_ID}/webrtc" class="ng-scope" src="http://127.0.0.1:8083/stream/{STREAM_ID}/channel/{CHANNEL_ID}/webrtc">
</iframe>
```

Thank you for your time,

Antonio

**Comment by allenporter** [comment]
Check out the examples directory under docs/ as it has an example of a webrtc stream. (You don't just refer to the url like that, you need JavaScript to start a webrtc player)

**Comment by antoniosteiger** [comment]
Hi Allen,

I just looked at it, thanks for the pointer. If I understand this correctly, I just need a few lines of javascript code that actually give me the webrtc player and serve that to a website through the <video> html. This website is then what I can actually embed on other websites, correct?

**Comment by allenporter** [comment]
I'd say, get the html/javascript for the player working, then you can try to embed that in an iframe.
