### ISSUE TITLE
Green image?

### ISSUE THREAD

**Issue by cmer** [deepch/RTSPtoWeb#21]
Hi there,

I am getting a green corrupted image on some of my cameras like such:

<img width="1107" alt="CleanShot 2021-02-11 at 12 27 08@2x" src="https://user-images.githubusercontent.com/412/107673973-788d7d00-6c64-11eb-80f1-470b6c232bfe.png">

With debug logs enabled, I am seeing many "Unsupported Intervaled data packet". Not sure if it's related? See logs: https://pastebin.com/yr4dnU2M -- restarting the camera brings back the image, but it eventually becomes green again. Not sure when/why it does become green.

VLC always shows the stream perfectly. The same stream also works fine with your RTSPtoWSMP4f project.

**Comment by deepch** [comment]
Apparently there is an error somewhere, you can give access to your rtsp stream?  I will fix it.

**Comment by cmer** [comment]
Thanks a lot! I just sent you an email with the credentials.
