### ISSUE TITLE
WebRTC offer requires form-data

### ISSUE THREAD

**Issue by timurkhakhalev** [deepch/RTSPtoWeb#215]
Hi! Please clarify in your API Documentation for WebRTC that your server is waiting for **form-data** info which needs to include: 'data': 'base64 encoded sdp offer'.
Its takes me very much hours to understand what I do wrong because I got error "SetRemoteDescription called with no ice-ufrag" every time because I used simple body json data to pass SDP offer.

**Comment by allenporter** [comment]
It would be great if you sent an update to the documentation!

**Comment by allenporter** [comment]
https://github.com/deepch/RTSPtoWeb/blob/master/docs/api.md

```The request is an HTTP POST with a parameter data that is a base64 encoded SDP offer (e.g. v=0...) from a WebRTC client.```

**Comment by timurkhakhalev** [comment]
> https://github.com/deepch/RTSPtoWeb/blob/master/docs/api.md
> 
> `The request is an HTTP POST with a parameter data that is a base64 encoded SDP offer (e.g. v=0...) from a WebRTC client.`

Yeah I mean it would be greate if you clarify that it must be [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData)

**Comment by allenporter** [comment]
Yeah I'm suggesting your contribution would be welcome to that page. (It seems perfectly clear to me, so an outside perspective could do a better job at clarifying what's missing.) Send an edit!
