### ISSUE TITLE
all client will auto-offline after 30s?

### ISSUE THREAD

**Issue by cgoder** [deepch/RTSPtoWeb#22]
thx for your good job~

https://github.com/deepch/RTSPtoWeb/blob/2be23e9a433112a097f43cb78f6956c4b108021b/storageClient.go#L58

count  clients why not like this:
`	if len(channelTmp.clients) > 0 {
		return true
	}`

this mean all client will auto-offline after 30s?

**Comment by deepch** [comment]
evry hit http ts seq and update
channelTmp.clients = time.Now()

if (no ack) > 30  == offline

**Comment by cgoder** [comment]
thx~

maybe this is code has or not clients exist, 
clients status update by another routine?

**Comment by deepch** [comment]
I will check it later.
