### ISSUE TITLE
RTSP push instead of pull

### ISSUE THREAD

**Issue by HenriqueOtsuka** [deepch/RTSPtoWeb#223]
Hey guys, 

I really liked this project and I want to push a RTSP stream, not pull it.

How does it works?

I already published in my encoder with rtsp://MY_IP:MY_PORT/stream/channel_id

What should I do to this stream appear in my dashboard?

**Comment by JeDiE99** [comment]
Try with https://github.com/aler9/rtsp-simple-server

**Comment by HenriqueOtsuka** [comment]
Thanks!!

It worked really well.
