### ISSUE TITLE
WebRTC Codec Not Supported

### ISSUE THREAD

**Issue by Abdeladim101Basraoui** [deepch/RTSPtoWeb#227]
I'm using 3 RTSP cam link 2 are *Success connection RTSP* but a 2 they got me the above error
`INFO[2022-10-03T22:50:45+01:00] Success connection RTSP                       call=Start channel=0 func=StreamServerRunStream module=core stream=246e929c-f254-4ffc-af75-a4eb2735b616
2022/10/03 22:50:50 Set ICEServers [stun:stun.l.google.com:19302]
ERRO[2022-10-03T22:50:51+01:00] WebRTC Codec Not Supported                    call=WritePacket channel=0 func=HTTPAPIServerStreamWebRTC module=http_webrtc stream=246e929c-f254-4ffc-af75-a4eb2735b616
2022/10/03 22:50:56 Set ICEServers [stun:stun.l.google.com:19302]
ERRO[2022-10-03T22:50:57+01:00] WebRTC Codec Not Supported                    call=WritePacket channel=0 func=HTTPAPIServerStreamWebRTC module=http_webrtc stream=246e929c-f254-4ffc-af75-a3eb9735b616
^CINFO[2022-10-03T22:51:03+01:00] Server receive signalinterrupt                func=main module=main
2022/10/03 22:51:03 [TEARDOWN rtsp://xxx:PORT/user=XXX_channel=1_stream=0.sdp/ RTSP/1.0
CSeq: 5
Session: 32345601
]
`

**Comment by fuzunspm** [comment]
did you find a solution?
