### ISSUE TITLE
Stream Stop after 15 seconds

### ISSUE THREAD

**Issue by daltonjoi** [deepch/RTSPtoWeb#23]
I have some streams that start and stop after 15 seconds , if i reload and restart , play only 15 seconds again.

**Comment by daltonjoi** [comment]
Solved adjusting stream parameters

![h264](https://user-images.githubusercontent.com/28409055/110256672-d7e76000-7f78-11eb-835f-8c764065c1a3.png)

**Comment by jerrysabu** [comment]
> Solved adjusting stream parameters
> 
> ![h264](https://user-images.githubusercontent.com/28409055/110256672-d7e76000-7f78-11eb-835f-8c764065c1a3.png)

where can i get the settings page ?
