### ISSUE TITLE
How to serve https

### ISSUE THREAD

**Issue by henryolade** [deepch/RTSPtoWeb#242]
Followed the installation instruction but i am not able to run it on https

**Comment by rogeriocassares** [comment]
Hi! I am using HAProxy and it is working.

Have you ever tried?

**Comment by tiaomail** [comment]
This configuration works for me:
`"server":{
      "debug":true,
      "log_level":"info",
      "http_demo":true,
      "http_debug":true,
      "http_login":"demo",
      "http_password":"demo",
      "http_port":":8083",
      "rtsp_port":":554",
      "https": true,
      "https_auto_tls": false,
      "https_auto_tls_name": "",
      "https_cert": "server.crt",
      "https_key": "server.key",
      "https_port": ":443"
   },`

**Comment by henryolade** [comment]
@tiaomail that works :)
