### ISSUE TITLE
Stream sporadicly not working across all browsers

### ISSUE THREAD

**Issue by stefanetzkorn** [deepch/RTSPtoWeb#245]
I am using the latest Build running in a docker container, the Problem also occurs without using Docker and running it normal.
For the website i am using the example provided in https://github.com/deepch/RTSPtoWeb/tree/master/docs/examples/webrtc

Sometimes the stream just does not load. I already testet it with Android (Chrome), Apple (Safari), Chrome and Firefox on Windows.
Here is the error i am getting in Chrome whenever the stream does not start:
![Error Chrome](https://user-images.githubusercontent.com/4946777/200324155-9a891832-8355-4be3-8495-51c88d5770b9.png)

At the same time the following error comes up on the server itself:
`level=error msg=gatherCompletePromise wait" call=WriteHeader channel=0 func=HTTPAPIServerStreamWebRTC module=http_webrtc stream=MAINSTREAM`

Its random whenever it will work or not, sometimes i need to refresh the page a few times before it works, somtimes it works right away.

**Comment by VitalyVaryvdin** [comment]
Getting the same issue on random streams every time
Did you manage to solve this?
