### ISSUE TITLE
Display in React?

### ISSUE THREAD

**Issue by austin-InDro** [deepch/RTSPtoWeb#251]
Hello,
I've copied your `webrtc` example into a React Web App. However, I am unable to get the system to display. Has anyone else been able to integrate this solution before? This is my code at the moment. It may be a simple answer, sorry, not very good at TS / React yet. I've seen comments about possibly needing hooks since there is a Script input from `main.js`?

```TypeScript
  useEffect(() => {
    // const script = document.createElement("script");
    // script.src = "main.js";
    // script.async = true;
    // document.body.appendChild(script);
    
    renderDone?.();
    // return () => {
    //   document.body.removeChild(script);
    // }
  }, [renderDone]);

  return (
    <div>
      <div>
        <input type="hidden" name="webrtc-url" id="webrtc-url"
            value="http://10.13.13.22:8083/stream/front/channel/0/webrtc"/>

        <video id="webrtc-video" autoPlay muted playsInline controls
        style={{width: "50%", height: "50%"}}></video>

        <script src="main.js"></script>
        </div>
    </div>
  );
}
```

Any help would be greatly appricated.

**Comment by vdalex25** [comment]
you can see example of react usage [here](https://github.com/vdalex25/rtsp-to-web-player)
