### ISSUE TITLE
What is the login info required to access <server:port>/streams

### ISSUE THREAD

**Issue by Thien223** [deepch/RTSPtoWeb#253]
Awsome project, Thank for your efforts. 

I'm trying to create separate html page for each camera, in order to be used in other place rather than only RTSOtoWeb webpage.

then I tried to access `http://192.168.100.50:8104/streams`, but it requires ID and password to process.

What is the account used to log in to this page?
Please help, thank you.

**Comment by allenporter** [comment]
Default https://github.com/deepch/RTSPtoWeb/blob/d3918d4a9cd293418db7e6bdd51c50263346c069/config.json#L7 is demo / demo

**Comment by Thien223** [comment]
@allenporter Thank you so much 😙
