### ISSUE TITLE
How do I get a published stream server URL?

### ISSUE THREAD

**Issue by Dryices** [deepch/RTSPtoWeb#258]
I want to embed the published stream into my own application using the published stream URL. My stream was initially in RTSP format and I want to stream using WebRTC, is it possible to get a URL such as http://localhost/stream_name/stream1?

**Comment by seededplyr** [comment]
the video endpoints are documented here: https://github.com/deepch/RTSPtoWeb/blob/master/docs/api.md#webrtc  an example is also available: https://github.com/deepch/RTSPtoWeb/tree/master/docs/examples/webrtc
