### ISSUE TITLE
configuration doubt

### ISSUE THREAD

**Issue by avico78** [deepch/RTSPtoWeb#263]
setup:

RTSPToWeb+ HA running on dockers on server A
Frigate - docker running on server B

Home assistant : 
RTSPtoWebRTC installed and connecting to RTSPToWeb ,
The result are good on HA .

Questions:
I think it make sense to let friagte use RTSPToWeb camera streaming ,
as now Frigdate connect to the cameras by itself and I'm trying to understrand 
what would be approach to do it ,
Can frigate use the camera streaming from RTSPToWeb ?how I should do it (As at current the camera configure in HA and using the 
RTSPtoWebRTC i didnt had to do anything on RTSPToWeb docker

**Comment by allenporter** [comment]
Seems like a question for frigate?

**Comment by avico78** [comment]
@allenporter - sorry for reopen , maybe i need ton rephrase my question ,
Can i set the cameras streams in RTSPToWeb docker and reuse the stream in other application?
(same as go2rtc provide)
