### ISSUE TITLE
transport.go:19:2: package io/fs is not in GOROOT 

### ISSUE THREAD

**Issue by wendy2702** [deepch/RTSPtoWeb#265]
Hi,

i just started with RTSPtoWeb and cloned the Project to a new Debian 11 installation.

Starting the "server" is got this Error:

```
GO111MODULE=on go run *.go
../go/pkg/mod/golang.org/x/net@v0.4.0/http2/transport.go:19:2: package io/fs is not in GOROOT (/usr/lib/go-1.15/src/io/fs)

```

Can somebody please let me know whats wrong?

I did not made any changed to config or anything else. On the same installation I`m able to start RTPStoWebRTC without problems.

**Comment by allenporter** [comment]
You may need to try a newer version of go

**Comment by wendy2702** [comment]
Installed latest Version of GO and error is gone.  

Thanks
