### ISSUE TITLE
Authorization play video

### ISSUE THREAD

**Issue by mboekhold** [deepch/RTSPtoWeb#271]
Hello,

I am really excited about this project and have been looking forward to using the video authorization feature. Could you please clarify the steps for using this feature? I want to make sure I am using it correctly and effectively"

I enabled the token

`"token": {
"enable": true,
"backend": "http://127.0.0.1:8000/watch"
}`

I tried requesting a video endpoint for hls 
`http://127.0.0.1:8083/stream/Mobotix01/channel/0/hls/live/index.m3u8?token=my_key`

but it does not forward the token to the backend, what am i missing?

Thanks for your help :)

**Comment by volkankoc** [comment]
I want to learn this too
