### ISSUE TITLE
Remote WebRTC Support

### ISSUE THREAD

**Issue by jsheo96** [deepch/RTSPtoWeb#289]
Hi, I'm struggling with making my ip camera available from remote computer. 

Here's my setting.
I have an IP camera that only supports RTSP streaming. and the camera is connected to a computer.
Since the computer is connected to the internet through a router, remote users cannot directly access to the IP camera without port forwarding. 
So, I decided to use WebRTC because I don't want to make port forwarding.
I installed coturn server, signaling server and web page server in my AWS EC2 instance.
I've used this repository to convert the RTSP streaming from the camera to WebRTC. 
and I confirmed it's working on local web browser.
Then I obtained the SDP of the stream by requesting HTTP POST method to my webrtc endpoint(http://localhost:8083/stream/demo/channel/0/webrtc).
The SDP is sent to the browser opened by remote computer through signaling server.
However, the video player in the web page does not play the stream at all. It only shows loading.

My situation is very similar to this (https://github.com/deepch/RTSPtoWebRTC/issues/162). but the answer(changing stun server) didn't work.

I've read all the related issue about this however, I couldn't find a way to resolve this. 
Thank you in advance.

**Comment by LiangHuangBC** [comment]
> I solved this issue. I added ICE candidates to browser's offer SDP message and send it directly to RTSPtoWeb server. by HTTP POST method. and got the answer SDP with ICE candidates. I also tried other things, but I think sending SDP with candidate was most important.

How did you make it, just concat two string?  offerSdp+candidate? port it buy http?

**Comment by allenporter** [comment]
Here is an example of how I've done this before:

https://github.com/home-assistant/frontend/blob/8cf8c416980636bfb7c89c87a78bc436f7a84534/src/components/ha-web-rtc-player.ts#L117

**Comment by LiangHuangBC** [comment]
Thanks for you reply. I tried this solution, and I can get answerSDP with candidate. If my laptop is in same LAN with RTSPToWeb server, Video shows with no problem, but If they are on different LAN, connect with internet, video is blank. I am running RTSPToWeb in container. Candidate in answerSDP is :

       a=candidate:1387070617 1 udp 2130706431 192.168.20.103 39157 typ host
       a=candidate:1387070617 2 udp 2130706431 192.168.20.103 39157 typ host
       a=candidate:233762139 1 udp 2130706431 172.17.0.1 42652 typ host
       a=candidate:233762139 2 udp 2130706431 172.17.0.1 42652 typ host
       a=candidate:3933351989 1 udp 1694498815 173.212.111.193 48401 typ srflx raddr 0.0.0.0 rport 48401
       a=candidate:3933351989 2 udp 1694498815 173.212.111.193 48401 typ srflx raddr 0.0.0.0 rport 48401

Any idea about this?

**Comment by LiangHuangBC** [comment]
Solved this issue. Before sending offer sdp, need to wait 2 seconds for the candidate gathering.

**Comment by Y-k-Y** [comment]
Facing same issue but both changing stun server and appending candidate didn't work for me.
@LiangHuangBC @jsheo96  What version of server did you guys use?
