### ISSUE TITLE
Binary Install Instructions Not Working

### ISSUE THREAD

**Issue by dbq-andersons** [deepch/RTSPtoWeb#29]
I am attempting a binary install as described in the README.md, but I cannot find anything in the releases directory.  Is a binary install still an option?  If so, please give a github noob some guidance :)

Thanks,

Bill

**Comment by deepch** [comment]
What OS are you installing under?

**Comment by dbq-andersons** [comment]
Ubuntu 20.04.2 LTS. 

Thanks,

Bill

**Comment by deepch** [comment]
### Download Source

1. Download source
   ```bash 
   $ git clone https://github.com/deepch/RTSPtoWeb  
   ```
3. CD to Directory
   ```bash
    $ cd RTSPtoWeb/
   ```
4. Test Run
   ```bash
    $ GO111MODULE=on go run *.go
   ```
5. Open Browser
    ```bash
    open web browser http://127.0.0.1:8083 work chrome, safari, firefox
    ```

if you need binary run command on source directory

 GO111MODULE=on go build *.go
