### ISSUE TITLE
WebRTC Url

### ISSUE THREAD

**Issue by goktugbati** [deepch/RTSPtoWeb#40]
Hi,
First of all I want to thank you guys for this very useful project.
I have two questions about the project
1. I want to display the webrtc in another app using html tags but I need the url to a specific channel and I couldn't find it, can you possibly share the url pattern?
2. When I use http://127.0.0.1:8083/pages/player/webrtc/demo/0 I don't see any delays but when I go to http://127.0.0.1:8083/pages/multiview/full I see approximately 2 seconds of delay. Can I possibly avoid the delay by changing configurations ? 

I'm new to video streaming protocols, sorry if the questions are nonsense.
Thanks in advance

**Comment by dj-documentation** [comment]
See #52 for a WebRTC example
