### ISSUE TITLE
config generation api bug

### ISSUE THREAD

**Issue by lfarkas** [deepch/RTSPtoWeb#42]
- if we delete all streams from the config (with the api call eg: 
```curl --header "Content-Type: application/json" \
  --request POST \
  --data '["0678af02-701f-48f8-8fb8-2c0c3e0a1a02", "2a787219-dda4-41ff-aded-e123cb5fc4ea", "577f167d-d560-45d5-b71f-26f6e48228b5", "57f4a2d2-bac4-4bff-b6c8-f5eef58c95d5", "af089982-0a81-4084-ad89-3c0ea6c32c46", "cc5a44ed-c5b3-4485-b0b0-38aeea78a291"]' http://demo:demo@127.0.0.1:80/streams/multi/control/delete
```
- then into the config in the stream part there will be a "null" in the steam section. this not cause problem and working until we restart the rtsp-to-web server
- if we restart the service and then no longer be able to add new stream through the api.
- if we replace the null with {} then we able to add new stream through the api.

it should have to fix.
anyway sometimes it's working when i change http_debug to true and loglevel to info. it seems to me some kind of timing issue. and we can reproduce it now (even though it was very difficult to find the problem)

**Comment by deepch** [comment]
thx, fixed
