### ISSUE TITLE
Stream does not play on the web

### ISSUE THREAD

**Issue by PittYao** [deepch/RTSPtoWeb#44]
Hello :
### My stream encoder is like this ：

- Video encoder : H264-MPEG-4 AVC 

- Audio encoder : MPEG AAC
  - Sampling Rate：48000 

![image](https://user-images.githubusercontent.com/26101917/124690045-34995e00-df0c-11eb-976c-a0c7e4771d52.png)

### console like this:
![image](https://user-images.githubusercontent.com/26101917/124690102-4418a700-df0c-11eb-858f-d0f6b101252c.png)

**Comment by deepch** [comment]
Can you organize access to your stream?
