### ISSUE TITLE
When trying to use webrtc I receive 404?

### ISSUE THREAD

**Issue by JTzLinux** [deepch/RTSPtoWeb#440]
Hello everyone I recently found this project (and I like it a lot) that I can get an rtsp stream and convert it to whatever I want it to be I wanted to use it for my klipper and have all cameras in a all in one page to see but sadly when I tried to use the webrtc api to add it for my klipper (because the webrtc has the least lag in my tests) I attempted to use it but I keep on getting an 404 not found
config.json:
```
{
  "server": {
    "debug": true,
    "http_debug": false,
    "http_demo": true,
    "http_dir": "web",
    "http_login": "demo",
    "http_password": "demo",
    "http_port": ":8083",
    "https": false,
    "https_auto_tls": false,
    "https_auto_tls_name": "",
    "https_cert": "server.crt",
    "https_key": "server.key",
    "https_port": ":443",
    "ice_servers": [],
    "log_level": "debug",
    "rtsp_port": ":5541",
    "token": {
      "backend": "http://127.0.0.1/test.php"
    },
    "defaults": {
      "audio": true
    }
  },
  "streams": {
    "videoMain": {
      "channels": {
        "0": {
          "url": "rtsp://stream:<Password>@10.1.10.74:554/videoMain",
          "debug": false,
          "audio": false
        }
      },
      "name": "111111111"
    }
  }
}
```
it works just fine on the online dashboard

**Comment by JTzLinux** [comment]
Update: so I just noticed I needed to post and also apss data but it still does not really work I get an 200 but I receive this weird block of text:
`dj0wDQpvPS0gODEzODgxNTk5MTE0MTM0Nzg0MSAxNzA4Njk2Mjc3IElOIElQNCAwLjAuMC4wDQpzPS0NCnQ9MCAwDQphPWZpbmdlcnByaW50OnNoYS0yNTYgQzc6MTM6MDQ6NUM6NjI6MzY6NEE6OUQ6OUQ6QUQ6Q0U6ODM6MDM6OEU6Mzg6NUM6NTA6MEY6QkI6MDk6QzA6OTA6MjI6RTE6NDU6NUQ6N0U6NDk6Nzk6QUY6NDU6QzkNCmE9Z3JvdXA6QlVORExFIDAgMQ0KbT1hdWRpbyA5IFVEUC9UTFMvUlRQL1NBVlBGIDEwOSA5IDAgOA0KYz1JTiBJUDQgMC4wLjAuMA0KYT1zZXR1cDphY3RpdmUNCmE9bWlkOjANCmE9aWNlLXVmcmFnOm5IRmdWZURzWXlvTWVsTXENCmE9aWNlLXB3ZDpWSGJBckNkclJSV2hwcmVmSE16UktCbXpVQVBsZW1DUQ0KYT1ydGNwLW11eA0KYT1ydGNwLXJzaXplDQphPXJ0cG1hcDoxMDkgb3B1cy80ODAwMC8yDQphPWZtdHA6MTA5IG1heHBsYXliYWNrcmF0ZT00ODAwMDtzdGVyZW89MTt1c2VpbmJhbmRmZWM9MQ0KYT1ydHBtYXA6OSBHNzIyLzgwMDAvMQ0KYT1ydHBtYXA6MCBQQ01VLzgwMDANCmE9cnRwbWFwOjggUENNQS84MDAwDQphPXJlY3Zvbmx5DQphPWNhbmRpZGF0ZTo3MTM0ODQ3MSAxIHVkcCAyMTMwNzA2NDMxIDEwLjIwLjAuMjI2IDQ0ODgzIHR5cCBob3N0DQphPWNhbmRpZGF0ZTo3MTM0ODQ3MSAyIHVkcCAyMTMwNzA2NDMxIDEwLjIwLjAuMjI2IDQ0ODgzIHR5cCBob3N0DQphPWNhbmRpZGF0ZTo0MDQ5NjU4ODY4IDEgdWRwIDE2OTQ0OTg4MTUgMTA5LjQzLjE3Ni4yNDQgMzA4NDEgdHlwIHNyZmx4IHJhZGRyIDAuMC4wLjAgcnBvcnQgNDk4MjENCmE9Y2FuZGlkYXRlOjQwNDk2NTg4NjggMiB1ZHAgMTY5NDQ5ODgxNSAxMDkuNDMuMTc2LjI0NCAzMDg0MSB0eXAgc3JmbHggcmFkZHIgMC4wLjAuMCBycG9ydCA0OTgyMQ0KYT1lbmQtb2YtY2FuZGlkYXRlcw0KbT12aWRlbyA5IFVEUC9UTFMvUlRQL1NBVlBGIDEyMCAxMjEgMTI2IDEyMw0KYz1JTiBJUDQgMC4wLjAuMA0KYT1zZXR1cDphY3RpdmUNCmE9bWlkOjENCmE9aWNlLXVmcmFnOm5IRmdWZURzWXlvTWVsTXENCmE9aWNlLXB3ZDpWSGJBckNkclJSV2hwcmVmSE16UktCbXpVQVBsZW1DUQ0KYT1ydGNwLW11eA0KYT1ydGNwLXJzaXplDQphPXJ0cG1hcDoxMjAgVlA4LzkwMDAwDQphPWZtdHA6MTIwIG1heC1mcz0xMjI4ODttYXgtZnI9NjANCmE9cnRjcC1mYjoxMjAgbmFjayANCmE9cnRjcC1mYjoxMjAgbmFjayBwbGkNCmE9cnRjcC1mYjoxMjAgY2NtIGZpcg0KYT1ydGNwLWZiOjEyMCBnb29nLXJlbWIgDQphPXJ0Y3AtZmI6MTIwIHRyYW5zcG9ydC1jYyANCmE9cnRwbWFwOjEyMSBWUDkvOTAwMDANCmE9Zm10cDoxMjEgbWF4LWZzPTEyMjg4O21heC1mcj02MA0KYT1ydGNwLWZiOjEyMSBuYWNrIA0KYT1ydGNwLWZiOjEyMSBuYWNrIHBsaQ0KYT1ydGNwLWZiOjEyMSBjY20gZmlyDQphPXJ0Y3AtZmI6MTIxIGdvb2ctcmVtYiANCmE9cnRjcC1mYjoxMjEgdHJhbnNwb3J0LWNjIA0KYT1ydHBtYXA6MTI2IEgyNjQvOTAwMDANCmE9Zm10cDoxMjYgcHJvZmlsZS1sZXZlbC1pZD00MmUwMWY7bGV2ZWwtYXN5bW1ldHJ5LWFsbG93ZWQ9MTtwYWNrZXRpemF0aW9uLW1vZGU9MQ0KYT1ydGNwLWZiOjEyNiBuYWNrIA0KYT1ydGNwLWZiOjEyNiBuYWNrIHBsaQ0KYT1ydGNwLWZiOjEyNiBjY20gZmlyDQphPXJ0Y3AtZmI6MTI2IGdvb2ctcmVtYiANCmE9cnRjcC1mYjoxMjYgdHJhbnNwb3J0LWNjIA0KYT1ydHBtYXA6MTIzIHVscGZlYy85MDAwMA0KYT1ydGNwLWZiOjEyMyBuYWNrIA0KYT1ydGNwLWZiOjEyMyBuYWNrIHBsaQ0KYT1ydGNwLWZiOjEyMyBjY20gZmlyDQphPXJ0Y3AtZmI6MTIzIGdvb2ctcmVtYiANCmE9cnRjcC1mYjoxMjMgdHJhbnNwb3J0LWNjIA0KYT1leHRtYXA6NyBodHRwOi8vd3d3LmlldGYub3JnL2lkL2RyYWZ0LWhvbG1lci1ybWNhdC10cmFuc3BvcnQtd2lkZS1jYy1leHRlbnNpb25zLTAxDQphPXNzcmM6MTY5OTQxNDExNyBjbmFtZTpwaW9uLXZpZGVvDQphPXNzcmM6MTY5OTQxNDExNyBtc2lkOnBpb24tdmlkZW8gcGlvbi1ydHNwLXZpZGVvDQphPXNzcmM6MTY5OTQxNDExNyBtc2xhYmVsOnBpb24tdmlkZW8NCmE9c3NyYzoxNjk5NDE0MTE3IGxhYmVsOnBpb24tcnRzcC12aWRlbw0KYT1tc2lkOnBpb24tdmlkZW8gcGlvbi1ydHNwLXZpZGVvDQphPXNlbmRyZWN2DQo=`

**Comment by HDTS1** [comment]
Read through [here](https://github.com/deepch/RTSPtoWeb/issues/431) it will help you achieve what you need.

**Comment by JTzLinux** [comment]
> Read through [here](https://github.com/deepch/RTSPtoWeb/issues/431) it will help you achieve what you need.

Thanks it helped me a lot <3
