### ISSUE TITLE
Lots of errors on GO111MODULE=on go run *.go

### ISSUE THREAD

**Issue by DavidMR91** [deepch/RTSPtoWeb#51]
When I make it: 

GO111MODULE=on go run *.go

The shell returns:

hlsFragment.go:6:2: cannot find package "github.com/deepch/vdk/av" in any of:
	/usr/lib/go-1.10/src/github.com/deepch/vdk/av (from $GOROOT)
	/home/eurek/go/src/github.com/deepch/vdk/av (from $GOPATH)
apiHTTPHLSLL.go:4:2: cannot find package "github.com/deepch/vdk/format/mp4f" in any of:
	/usr/lib/go-1.10/src/github.com/deepch/vdk/format/mp4f (from $GOROOT)
	/home/eurek/go/src/github.com/deepch/vdk/format/mp4f (from $GOPATH)
streamCore.go:8:2: cannot find package "github.com/deepch/vdk/format/rtspv2" in any of:
	/usr/lib/go-1.10/src/github.com/deepch/vdk/format/rtspv2 (from $GOROOT)
	/home/eurek/go/src/github.com/deepch/vdk/format/rtspv2 (from $GOPATH)
apiHTTPHLS.go:7:2: cannot find package "github.com/deepch/vdk/format/ts" in any of:
	/usr/lib/go-1.10/src/github.com/deepch/vdk/format/ts (from $GOROOT)
	/home/eurek/go/src/github.com/deepch/vdk/format/ts (from $GOPATH)
apiHTTPWebRTC.go:6:2: cannot find package "github.com/deepch/vdk/format/webrtcv3" in any of:
	/usr/lib/go-1.10/src/github.com/deepch/vdk/format/webrtcv3 (from $GOROOT)
	/home/eurek/go/src/github.com/deepch/vdk/format/webrtcv3 (from $GOPATH)
apiHTTPRouter.go:8:2: cannot find package "github.com/gin-gonic/autotls" in any of:
	/usr/lib/go-1.10/src/github.com/gin-gonic/autotls (from $GOROOT)
	/home/eurek/go/src/github.com/gin-gonic/autotls (from $GOPATH)
apiHTTPChannel.go:4:2: cannot find package "github.com/gin-gonic/gin" in any of:
	/usr/lib/go-1.10/src/github.com/gin-gonic/gin (from $GOROOT)
	/home/eurek/go/src/github.com/gin-gonic/gin (from $GOPATH)
storageConfig.go:10:2: cannot find package "github.com/hashicorp/go-version" in any of:
	/usr/lib/go-1.10/src/github.com/hashicorp/go-version (from $GOROOT)
	/home/eurek/go/src/github.com/hashicorp/go-version (from $GOPATH)
storageConfig.go:12:2: cannot find package "github.com/liip/sheriff" in any of:
	/usr/lib/go-1.10/src/github.com/liip/sheriff (from $GOROOT)
	/home/eurek/go/src/github.com/liip/sheriff (from $GOPATH)
apiHTTPChannel.go:5:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/usr/lib/go-1.10/src/github.com/sirupsen/logrus (from $GOROOT)
	/home/eurek/go/src/github.com/sirupsen/logrus (from $GOPATH)
apiHTTPMSE.go:8:2: cannot find package "golang.org/x/net/websocket" in any of:
	/usr/lib/go-1.10/src/golang.org/x/net/websocket (from $GOROOT)
	/home/eurek/go/src/golang.org/x/net/websocket (from $GOPATH)

**Comment by vdalex25** [comment]
your go version < 1.11 ?

**Comment by DavidMR91** [comment]
It was due to a problem with the golang.go installation. I have deleted and reinstalled and it has been resolved
