### ISSUE TITLE
RTMP push output

### ISSUE THREAD

**Issue by log-to-code** [deepch/RTSPtoWeb#56]
We could make use of RTMP push output to live stream to YouTube, Facebook, Twitter, and AWS MediaLive.

https://support.google.com/youtube/answer/2907883?hl=en
https://www.facebook.com/help/755943624557739
https://help.twitter.com/en/using-twitter/how-to-use-live-producer
https://docs.aws.amazon.com/medialive/latest/ug/rtmp-push-upstream.html
https://docs.aws.amazon.com/medialive/latest/ug/inputs-supported-formats.html

**Comment by log-to-code** [comment]
We can use ffmpeg or https://github.com/aler9/rtsp-simple-server to transmux RTSP to RTMP.

**Comment by deepch** [comment]
https://github.com/deepch/RTSPtoRTMP
as it?
