### ISSUE TITLE
Stream on external server

### ISSUE THREAD

**Issue by jovanjelic** [deepch/RTSPtoWeb#64]
Hi,
Awesome project!

How can I use RTSPtoWEB on server?
Problem is that frontend send POST to url: IP:8083 but that fails. 
Only way that works if url: localhost:8083, but that can only be used on server machine.  
I need clients to see stream.
Is there a way to start RTSPtoWEB on IP:8083? IP is IP of web server

**Comment by nightzjp** [comment]
Deploy the project directly on the web server, and then embed the front end into its own system through demo

**Comment by nightzjp** [comment]
The pressure of the server is transferred to the client. I use a 4-core 16g client, which can play more than 16 videos at the same time, and the server basically has no performance loss

**Comment by jovanjelic** [comment]
Problem was Firewall. You need to open port 8083 and setup TURN/STUN for production server. Issue can be closed now

**Comment by jovanjelic** [comment]
Maybe this information should be added in README.md

**Comment by rogeriocassares** [comment]
Yes, please, I am in some hours when I realize that. ahaha 

I am using with Docker. My port 8083 is open and I do not know hot to set the TURN server for production. Could anybody helpe me please?


Thanks!
