### ISSUE TITLE
ICE server in local network. SetRemoteDescription called with no ice-ufrag

### ISSUE THREAD

**Issue by jovanjelic** [deepch/RTSPtoWeb#66]
Hi,
I need to run streaming server in local network without internet connections. So camera is connected in LAN with the server. But I get the following error: "SetRemoteDescription called with no ice-ufrag" and I don't now how to fix it.
I don't need STUN/TURN servers for this setup. Please help

**Comment by kennyzhu2013** [comment]
ICE must be supported within SDP context.
