### ISSUE TITLE
404 error on webrtc video endpoint

### ISSUE THREAD

**Issue by mcquaas** [deepch/RTSPtoWeb#71]
I am getting a 404 error trying to access the webrtc video endpoint as marked in the API documentation.

**Comment by skeal** [comment]
Any news on this? Would really need this, too.

**Comment by allenporter** [comment]
WebRTC endpoint works for me. What endpoint? Have any extra details?

**Comment by skeal** [comment]
Could you paste your config for it as there might be some confusion about building the link?

**Comment by allenporter** [comment]
I followed https://github.com/deepch/RTSPtoWeb/blob/master/docs/api.md and got things working fine. Default config with a single RTSP stream added using the API following the example. If you have a specific detail of what you're trying and what's not working happy to give you a suggestion.

**Comment by skeal** [comment]
That's nice.. So here is the config and I try to call it by: http://<ip>:8083/stream/garten/channel/0/webrtc

`{
  "server": {
    "debug": true,
    "http_debug": false,
    "http_demo": true,
    "http_dir": "web",
    "http_login": "demo",
    "http_password": "demo",
    "http_port": ":8083",
    "https": false,
    "https_auto_tls": false,
    "https_auto_tls_name": "",
    "https_cert": "server.crt",
    "https_key": "server.key",
    "https_port": ":443",
    "log_level": "debug",
    "rtsp_port": ":5541",
    "token": {}
  },
  "streams": {
    "33235b12-ace1-46a8-a596-fff14a8bff27": {
      "channels": {
        "0": {
          "url": "rtsp://xxx:xxx@IP:554/ch1/main"
        }
      },
      "name": "haustuer"
    },
    "garten": {
      "channels": {
        "0": {
          "name": "ch1",
          "url": "rtsp://xxx:xxx@<ip>:554/ch1/main"
        }
      },
      "name": "gartenvideo"
    }
  }
`

**Comment by allenporter** [comment]
OK great, that looks fine.

My impression is you need to send a base64 encoded SDP offer as the post payload `data`. One of the 400s in the .go code are served when the offer is not in the correct format: https://github.com/deepch/RTSPtoWeb/blob/1673ada9fd6be04dd8e4d340f15dc566e0c6607a/apiHTTPWebRTC.go#L38

What kind of payload are you sending?

**Comment by skeal** [comment]
Ok now you got me. Thought I just have to call this URL in browser 

How then to use it properly? I want to include a single camera stream in browser/iframe

**Comment by allenporter** [comment]
You need a webrtc client, like In JavaScript. Maybe the examples here can help you:
https://github.com/deepch/RTSPtoWeb/tree/master/docs/examples/webrtc

**Comment by skeal** [comment]
That did it. Thank you so much! I'm not so deep into web dev :-)

Have a nice day!

**Comment by skeal** [comment]
Sorry for bothering again. On my PC (Windows/Chrome) the stream is shown. But not on my Android Tablet. The page just stays blank. Is there anything to do there?

**Comment by allenporter** [comment]
I'm not sure -- i think we'd need to dig in deeper in a separate issue, and perhaps its client side given other browsers have shown to work. I'm going to mark this as closed given the original issue was resolved.
