### ISSUE TITLE
MSE video freezes in Safari after first frame with avc1.4D001E and avc1.4D002A codecs

### ISSUE THREAD

**Issue by piercefaulkner** [deepch/RTSPtoWeb#90]

**Comment by deepch** [comment]
please share you stream I can fix it only debug live

**Comment by piercefaulkner** [comment]
UPDATE: The video doesn't work in Firefox either.

**Comment by piercefaulkner** [comment]
UPDATE 2: Nevermind, the video *does* work in Firefox.

**Comment by piercefaulkner** [comment]
UPDATE 2: Nevermind, the video *does* work in Firefox.
