### ISSUE TITLE
Publish releases & docker images

### ISSUE THREAD

**Issue by allenporter** [deepch/RTSPtoWeb#91]
I am going to redo https://github.com/deepch/RTSPtoWebRTC/issues/127 for RTSPtoWeb.

The steps are:
- Make a new `Dockerfile`
- Set up a new github action with [Github Images](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages)
- Issue a release using semvar for Major/Minor/Patch release following https://semver.org/

@deepch do you have a preference for what version is used for the first release? 1.0.0? 2.0.0?

**Comment by allenporter** [comment]
@deepch do you have a preference on the initial version released? is 1.0.0 ok?

**Comment by deepch** [comment]
@allenporter 1.0.0 is good
